export const ACTIONS = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_TO_NUMBER: "SET_TO_NUMBER",
  LIKE_POST: "LIKE_POST",
  MARK_POST: "MARK_POST",
  SET_ALL_POSTS: "SET_ALL_POSTS",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_SHOW_LOAD_MORE: "SET_SHOW_LOAD_MORE",
};
